### ISSUE TITLE
Help me i cant find the exe

### ISSUE THREAD

**Issue by Jeppepro1234** [FLUORESCENTXX/Zenith-Builder#7]
Help me i cant find the exe

**Comment by FLUORESCENTXX** [comment]
ur not meant to find the exe its meant to be on ur file folderr

**Comment by Jeppepro1234** [comment]
> ur not meant to find the exe its meant to be on ur file folderr

What do you mean, how do i execute the image logger then?

**Comment by FLUORESCENTXX** [comment]
Ur meant to make a stub then add it
