### ISSUE TITLE
Is not compiling

### ISSUE THREAD

**Issue by WppThomas** [FLUORESCENTXX/Zenith-Builder#9]
it says theres an error when I click compile but then i continue it anyway and there is no file when it has finished compiling.

**Comment by WppThomas** [comment]
![Capture](https://user-images.githubusercontent.com/105495936/168289478-bf065419-235c-47ce-a2b8-afe65866504e.PNG)

**Comment by FLUORESCENTXX** [comment]
Updating v1.4

**Comment by FLUORESCENTXX** [comment]
Adding v1.4 now.
